name: nimble
version: 0.0.1
author: csh <connorsharries96@gmail.com>
description: Lightweight plugin system for Dart
homepage: https://github.com/csh/nimble.dart
environment:
  sdk: '>=1.5.0'
dependencies:
  path: '>=1.2.1 <2.0.0'
  yaml: '^2.1.13'
  test: '^0.12.33'